#!/usr/bin/env bash

_crecord_completition() {
	local cur prev opts
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	#prev2="${COMP_WORDS[COMP_CWORD-2]}"

	case "${prev}" in
	"crecord")
		opts="record delete"
		COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
		;;
	"-d")
		compopt -o nospace
		COMPREPLY=( $(compgen -S "/" -d -- "${cur}") )
		;;
	*)
		return
		;;
	esac
}

complete -F _crecord_completition crecord
