#!/usr/bin/env bash
_crecord_completition() {
	if [ "${#COMP_WORDS[@]}" != "2" ]; then
		return
	fi
	COMPREPLY=($(compgen -W "record delete" "${COMP_WORDS[1]}"))
}

complete -F _crecord_completition crecord
