.TH crecord 1 "2018 November 3" "v0.4.3"
.SH NAME
crecord - record video streams from IP cameras
.SH SYNOPSYS
.B crecord
.I record
[\-c] [\-L] [\-q] [\-l | \-\-log] [\-h | \-\-help]
[\-t \fIsegment_time\fR]
[\-p \fIport\fR]
[\-d \fIdestination_folder\fR]
[\-s \fIsegment_start_number\fR]
[\-P \fIpath\fR]
[\-u | \-\-username \fIusername\fR]
[\-w | \-\-password \fIpassword\fR]
.PP
.B crecord
.I all
.PP
.B crecord
.I delete
[\-h | \-\-help] [\-y]
[\-d \fIdestination_folder\fR]
[\-m \fImin\fR]
[\-f \fIformat\fR]
.PP
.B crecord
.I uninstall
.SH DESCRIPTION
.B crecord
is a program…
.SH OPTIONS
.SS record
.TP
.B \-h, \-\-help
Print help message.
.TP
.B \-t \fIsegment_time
Split recordings in different files of \fIsegment_time\fR seconds.
.TP
.B \-p \fIport\fR
Set network port number. Default is 554 (RTSP).
.TP
.B \-d \fIdestination_folder\fR
Set where to output recording files. Default is \fI.\fR
.TP
.B \-c
If \fIdestination_folder\fR does not exist, create it.
.TP
.B \-l, \-\-log
Enable logging to a file called log.txt. You can find it in \fIdestination_folder\fR.
.TP
.B \-s \fIsegment_start_number\fR
File names have an iterate number which starts from 0 by default. You can change this behaviour and start from any number.
.TP
.B \-P \fIpath\fR
Set the RTSP path.
.TP
.B \-L
Enable loop execution. It is useful if the stream has frequent interruptions, in this case, \fBcrecord\fR restarts automatically and immediatly retry to record the stream.
.TP
.B \-u, \-\-username \fIusername\fR
Set RTSP username.
.TP
.B \-w, \-\-password \fIpassword\fR
Set RTSP password.
.TP
.B \-q
Enable quiet mode.
.SS delete
.TP
.B \-h, \-\-help
Print help message.
.TP
.B \-y
Say yes to all.
.TP
.B \-d \fIdestination_folder\fR
Say where files to delete are located.
.TP
.B \-m \fImin\fR
Delete files older than \fImin\fR.
.TP
.B \-f \fIformat\fR
Delete files with extension \fIformat\fR. Default is mp4.
.SH EXAMPLES
To record a video stream from 192.168.0.42
.PP
.nf
.RS
.RB $ " crecord 192.168.0.42"
.RE
.fi
.PP
Nifty, huh?
.PP
To record a video stream from 192.168.0.42/v1
.PP
.nf
.RS
.RB $ " crecord -P 'v1' 192.168.0.42"
.RE
.fi
.PP
.SH AUTHOR
Written by Alberto Amoruso.
.SH REPORTING BUGS
Report bugs to <alberto.am@me.com>
